import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/_components/Navbar";
import {ThemeProvider} from "@/components/theme-provider";
import Footer from "@/app/_components/Footer";
import {ClerkProvider} from "@clerk/nextjs";
import {ruRU} from "@clerk/localizations";
import React from "react";
import {Toaster} from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <ClerkProvider localization={ruRU}>
        <html lang="en" suppressHydrationWarning>
          <body className={inter.className}>
          <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
          >
              <Navbar />
                <div className="md:px-24 sm: px-10">
                  {children}
                </div>
              <Footer />
              <Toaster />
          </ThemeProvider>
          </body>
        </html>
      </ClerkProvider>
  );
}
